# practical 9B without error
from tkinter import *
def display():
    pass
w1=Tk()
w1.title('My App')

title=StringVar()
m1=Message(w1, textvariable=title,width=100)
title.set('Entre Your Details... ')

title=StringVar()
l1=Label(w1, text='name')

name=StringVar()
e1=Entry(w1, text=name)
l2=Label(w1, text='gender')
gender=IntVar()
r1=Radiobutton(w1, text='male', variable=gender, value=1)
r2=Radiobutton(w1, text='female',variable=gender,value=2)
l3=Label(w1,text='hobbies')
hobbies1=IntVar()
hobbies2=IntVar()
ch1=Checkbutton(w1, text='reading', variable=hobbies1)
ch2=Checkbutton(w1, text='writing', variable=hobbies2)
l4=Label(w1, text='percentage')
per=DoubleVar()
s1=Scale(w1, variable=per, orient=HORIZONTAL, length=300)
b1=Button(w1,text='Submit',command=display)
result=Label(w1)
m1.grid(row=0,column=0,columnspan=2)
l1.grid(row=1,column=0)
e1.grid(row=1,column=1)
l2.grid(row=2,column=0)
r1.grid(row=2,column=1)
r2.grid(row=2,column=2)
l3.grid(row=3,column=0)
ch1.grid(row=3,column=1)
ch2.grid(row=3,column=2)
l4.grid(row=4,column=0)
s1.grid(row=4,column=1,columnspan=2)
b1.grid(row=5,column=1)
result.grid(row=6,column=1,columnspan=2)
w1.mainloop()
